#!/bin/sh

touch "$HOME"/.psqlrc.local

ruby $HOME/dotfiles/install_vscode_extensions.rb
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false

# cp ~/dotfiles/dotfiles-precommit-hook ~/dotfiles/.git/hooks/pre-commit

reset -Q

if [ -f "$HOME/.git_template/HEAD" ] && \
  [ "$(cat "$HOME/.git_template/HEAD")" = "ref: refs/heads/main" ]; then
  echo "Removing ~/.git_template/HEAD in favor of defaultBranch" >&2
  rm -f ~/.git_template/HEAD
fi

# detect old OS X broken /etc/zshenv and suggest rename
if grep -qw path_helper /etc/zshenv 2>/dev/null; then
  dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)

  cat <<MSG >&2
Warning: \`/etc/zshenv' configuration file on your system may cause unexpected
PATH changes on subsequent invocations of the zsh shell. The solution is to
rename the file to \`zprofile':
  sudo mv /etc/{zshenv,zprofile}

(called from ${dir}/post-up:${LINENO})

MSG
fi

for dir in "$HOME"/.vim/*; do
  if [ -d "$dir" ]; then
    directory_name=$(basename "$dir")

    if [ ! -e "$HOME"/.config/nvim/"$directory_name" ]; then
      ln -sf "$dir" "$HOME"/.config/nvim/"$directory_name"
    fi
  fi
done

if [ ! -d "$HOME"/.fzf ]; then
  echo "Installing FZF"
  git clone --depth 1 https://github.com/junegunn/fzf.git "$HOME"/.fzf
  "$HOME"/.fzf/install
fi
